### ISSUE TITLE
Is reading FNSKU possible?

### ISSUE THREAD

**Issue by serdarbuyuktemiz-eva** [maslick/koder#23] opened 2021-12-30 08:57 UTC
What is an FNSKU?
https://www.shipcalm.com/blog/fnsku/

**Comment by maslick** [comment] 2021-12-30 09:08
Yes, just switch to the bar-code mode [here](https://qr.maslick.tech) and try to scan this example FNSKU code (taken from [here](http://www.philcovington.com/index.php/2017/05/26/do-i-need-to-send-my-supplier-my-products-upc-code/))
![fnsku](https://user-images.githubusercontent.com/5644706/147737608-608bd32c-16e1-432f-8e45-6ee45eed7c9d.png)

**Comment by maslick** [comment] 2021-12-30 09:47
As far as I understood FNSKU is a 10 digit CODE-128 barcode, so it should work with ``koder``.

**Comment by serdarbuyuktemiz-eva** [comment] 2021-12-30 16:23
i don't know the details about fnsku
from warehouse they gave me this example as not working...

![image](https://user-images.githubusercontent.com/95478931/147769609-9bc10c84-e9d6-458e-a000-0af25d2b1ae6.png)

can this type be implemented?
how long it can take?

**Comment by maslick** [comment] 2021-12-30 17:09
@serdarbuyuktemiz-eva post an example here, so it can be reproduced

**Comment by maslick** [comment] 2021-12-30 17:14
@serdarbuyuktemiz-eva your example works for me (both on a mobile phone and my laptop)

**Comment by sesam** [comment] 2021-12-30 17:15
That image looks visually like ITF 2-of-5. Maybe the text interpretation might be the issue.

**Comment by maslick** [comment] 2021-12-30 17:16
Make sure you have toggled the right-most button from qr -> bar

**Comment by maslick** [comment] 2022-01-05 05:57
@serdarbuyuktemiz-eva was your issue resolved? I am going to close this

**Closed by maslick** 2022-01-05 05:57 UTC

**Comment by serdarbuyuktemiz-eva** [comment] 2022-01-05 09:04
it is ok to close the issue.
maybe out mobile machines have low quality cameras 
but it is not read in our side...

**Comment by maslick** [comment] 2022-01-05 10:37
@serdarbuyuktemiz-eva for the record: I am testing on an iPhone 11 Pro
