### ISSUE TITLE
flying letters that looks like the matrix screen

### ISSUE THREAD

**Issue by erickaudet** [maslick/koder#36] opened 2022-01-10 15:16 UTC
After the 
`yarn run vanilla-js-live`
I get flying letters that looks like the matrix screen... ;-)
Any body got this?

**Comment by maslick** [comment] 2022-01-10 15:20
Please, provide a screenshot. Did you run ``yarn install`` before `yarn run vanilla-js-live`?

**Comment by maslick** [comment] 2022-01-12 09:17
closing due to not being able to reproduce the issue (not enough information)

**Closed by maslick** 2022-01-12 09:17 UTC
